### ISSUE TITLE
Sending Decred page needs margin fix

### ISSUE THREAD

**Issue by beatljuice** [decred/dcrandroid#305] opened 2019-01-17 02:40 UTC
The margins on the top of the Sending Decred page don't match the margins on the other pages, the text is too close to the edge. The fonts in the lower part of the page (Fee, Estimated Size, Balance After) also seem overly large, but seem to have proper margins.

**Comment by raedah** [comment] 2019-01-19 02:35
Please provide a screenshot.

**Comment by beatljuice** [comment] 2019-01-19 03:53
![image](https://user-images.githubusercontent.com/8432851/51421884-0caeb800-1b63-11e9-96b8-70305b4f983d.png)

**Comment by beatljuice** [comment] 2019-01-19 03:54
Moto Z3 Play is the phone.

**Comment by crux25** [comment] 2019-06-29 07:36
I can't reproduce the error described.

**Comment by C-ollins** [comment] 2019-11-27 23:40
Closed in #391

**Closed by C-ollins** 2019-11-27 23:40 UTC
